#version: "3.8"

services:
  retro_site:
    build: .
    container_name: retro_site
    restart: unless-stopped
    ports:
      - "12080:80"    # change en "8080:80" si tu as déjà quelque chose sur 80